easy_admin:
    entities:
        Inventairerdv:
            class: App\Entity\Inventairerdv
            form:
                fields:
                    - { property: 'rendezvous', type: 'association' }
                    - { property: 'reference', type: 'text' }
                    - { property: 'quantity', type: 'number' }
                    - { property: 'dateInsertion', type: 'datetime' }
