controllers:
    resource: ../src/Controller/
    type: attribute
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
change-password:
    path: /change-password
    controller: App\Controller\ChangePasswordController::changePassword